#!/usr/bin/env bash
#
# Copyright 2019 The zensational authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

set -euo pipefail

[[ -n "${ZEN_USER_HOME:+x}" ]] || export ZEN_USER_HOME="${HOME}/.zensational"
readonly ZEN_USER_HOME

declare -xr PROJECT_DIR="$(dirname "$0")"
if [[ -f "${PROJECT_DIR}/zen.json" ]]; then
  declare -xr ZEN_VERSION="$(grep '"version"' "${PROJECT_DIR}/zen.json" | head -n1 | grep -oE '[0-9](\.[0-9]+)+')"
else
  declare -xr ZEN_VERSION="1.41"
fi

[[ -n "${ZEN_HOME:+x}" ]] || export ZEN_HOME="${ZEN_USER_HOME}/dists/${ZEN_VERSION}"
readonly ZEN_HOME

dist_archive="${ZEN_HOME}.tar.gz"
if [[ ! -d "${ZEN_HOME}" ]]; then
  echo "Downloading zensational ${ZEN_VERSION} to \"${dist_archive}\"..."
  curl --create-dirs -Lso "${dist_archive}" "https://github.com/abc-inc/zensational/releases/download/${ZEN_VERSION}/zensational-${ZEN_VERSION}.tar.gz" || ret=$?
  if [[ "${ret:-0}" -ne 0 ]]; then
    echo "ERROR: Cannot download zensational distribution."
    exit "${ret}"
  fi

  if [[ -f "${dist_archive}" && ! -d "${ZEN_HOME}" ]]; then
    echo "Installing zensational ${ZEN_VERSION}..."
    tar -xzf "${dist_archive}" -C "${ZEN_USER_HOME}/dists"
    mv "${ZEN_USER_HOME}/dists/zensational-${ZEN_VERSION}" "${ZEN_HOME}"
    "${ZEN_HOME}/zen/bin/zen.sh" setup
  fi
fi

"${ZEN_HOME}/zen/bin/zen.sh" "$@"
